pool:
  vmImage: ubuntu-latest

stages:

- stage: BuildAndDeployToTst
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
    - template: templates/azure_release_pipeline.yml
      parameters:
        Environment: Tst
        # VariableGroup: MART-ACC
        # project_name: $(project_name)

- stage: BuildAndDeployToAcc
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  dependsOn: BuildAndDeployToTst
  jobs:
    - template: templates/azure_release_pipeline.yml
      parameters:
        Environment: Acc

- stage: BuildAndDeployToPrd
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  dependsOn: BuildAndDeployToAcc
  jobs:
    - template: templates/azure_release_pipeline.yml
      parameters:
        Environment: Prd

