pool:
  vmImage: "ubuntu-latest"

stages:
- stage: BuildAndDeployToAcc
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
  jobs:
  - job: Build
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'Hello world'
    # - template: templates/weekly_release_pipeline.yml
    #   parameters:
    #     Environment: Acc
        # VariableGroup: MART-ACC
        # project_name: $(project_name)

- stage: BuildAndDeployToPrd
  dependsOn: BuildAndDeployToAcc
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  jobs:
  - job: Build
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'Hello world'
    # - template: templates/weekly_release_pipeline.yml
    #   parameters:
    #     Environment: Prd
        # VariableGroup: MART-ACC
        # project_name: $(project_name)
