parameters:
- name: Environment
  type: string
  default: "EnvironmentName"

jobs:
- deployment: DeployTo${{parameters.Environment}}
  environment: ${{parameters.Environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - script: python3 ci_cd/databricks/templates/build_release.py
          workingDirectory: $(Build.SourcesDirectory)
          continueOnError: true

        - task: UsePythonVersion@0
          displayName: 'Use Python 3.7'
          inputs:
            versionSpec: 3.7

        # Install required Python modules.
        - task: CmdLine@2 
          displayName: 'Load Python Dependencies'
          inputs:
            script: pip3 install databricks-cli

        - task: CmdLine@2
          displayName: 'Configure databricks cli'
          inputs: 
            script: |
              databricks configure --token <<EOF
              https://adb-2309064528945260.0.azuredatabricks.net/
              dapi5f8f6498c8b24b7b499abc1d2be77d06-2
              EOF

        - task: CmdLine@2
          displayName: 'Export Databricks Workspace'
          continueOnError: true
          inputs: 
            script: |
              echo $(files)
              for add in $(files):
              do
                echo $add
              done
