parameters:
- name: Environment
  type: string
  default: "EnvironmentName"

jobs:
- deployment: DeployTo${{parameters.Environment}}
  environment: ${{parameters.Environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - task: UsePythonVersion@0
          displayName: 'Use Python 3.7'
          inputs:
            versionSpec: 3.7

        # Install required Python modules.
        - task: CmdLine@2 
          displayName: 'Load Python Dependencies'
          inputs:
            script: pip3 install databricks-cli

        - script: python3 ci_cd/databricks/templates/new_build_release.py
          workingDirectory: $(Build.SourcesDirectory)
          continueOnError: true
          env: 
            DATABRICKS_HOST: "https://adb-6038645435743090.10.azuredatabricks.net"
            DATABRICKS_TOKEN: "dapif9c592e3955ee3cb7edaf8bc406e99e5-2"
            ENV: ${{parameters.Environment}}

